version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USER:?error} #<admin-user>
            MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD:?error} #<admin-password>
            MONGO_INITDB_DATABASE: ${DATABASE_NAME:?error} #<database to create>
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro